// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Environment/Climbable/ClimbableObjectBase.h"
#include "LadderBase.generated.h"

class UInstancedStaticMeshComponent;
class UStaticMeshComponent;

/**
 * 
 */
UCLASS()
class UE5PROJECT_API ALadderBase : public AClimbableObjectBase
{
	GENERATED_BODY()
	
public:
	ALadderBase();

	const USceneComponent* GetTopExitTarget() const { return ClimbTopExitLocation; }
	FVector GetLadderForwardVector() const;
	FVector GetLadderRightVector() const;
	FVector GetLadderUpVector() const;
	FVector GetLadderTopEndpointWorld() const;

#pragma region Ladder Basic Composition
////////////////////////////////////
// Methods For Ladder Basic Composition
////////////////////////////////////
private:
	void ClearGeneratedLadder();
	void RebuildLadder();
	void BuildRuntimeGripData();
	bool HasValidGeneratedMeshes() const;
	void SetInitTopPosition();
	void SetInitBottomPosition();
	FVector GetGeometryPointInActorSpace(float Height) const;

protected:
	virtual void BeginPlay() override;

	virtual void OnConstruction(const FTransform& Transform) override;

////////////////////////////////////
// Variables For Ladder Basic Composition
////////////////////////////////////
protected:
	/** Root of the generated ladder body. Tilting this does not tilt the ground entry/exit targets. */
	UPROPERTY(VisibleAnywhere, Category = "Ladder|Geometry")
	TObjectPtr<USceneComponent> LadderGeometryRoot;

	/** All repeated ladder modules are rendered by this single instanced component. */
	UPROPERTY(VisibleAnywhere, Category = "Ladder|Geometry")
	TObjectPtr<UInstancedStaticMeshComponent> GeneratedLadderMesh;

	UPROPERTY(EditAnywhere, Category = "Ladder|Geometry", meta = (ClampMin = "1"))
	int32 LadderLevel = 1;

	UPROPERTY(EditAnywhere, Category = "Ladder|Geometry")
	FVector LadderScale = FVector::OneVector;

	UPROPERTY(EditAnywhere, Category = "Ladder|Geometry", meta = (Units = "cm"))
	float AdditionalHeight = 0.0f;

	/** Positive values lean the top of the ladder toward its local front (-X). */
	UPROPERTY(EditAnywhere, Category = "Ladder|Geometry", meta = (ClampMin = "-80.0", ClampMax = "80.0", Units = "deg"))
	float LadderTiltAngle = 0.0f;

	/** Bottom alignment point relative to the generated ladder's lower endpoint. */
	UPROPERTY(EditAnywhere, Category = "Ladder|Placement", meta = (Units = "cm"))
	FVector BottomEntryOffset = FVector(80.0f, 0.0f, 0.0f);

	/** Bottom interaction volume center relative to the generated ladder's lower endpoint. */
	UPROPERTY(EditAnywhere, Category = "Ladder|Placement", meta = (Units = "cm"))
	FVector BottomTriggerOffset = FVector(80.0f, 0.0f, 92.0f);

	/** One-release migration storage for components generated by the previous construction layout. */
	UPROPERTY(meta = (DeprecatedProperty, DeprecationMessage = "Generated modules now use GeneratedLadderMesh."))
	TArray<TObjectPtr<UStaticMeshComponent>> ClimbMeshes;

#pragma endregion
};
